In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def p2f(x):
    return float(x.strip('%'))/100

df = pd.read_csv("https://raw.githubusercontent.com/visualization-project-group/surprise-map-assignment/master/hate_crime.csv",usecols=['STATE_NAME', 'BIAS_DESC', 'DATA_YEAR'])
df3 = df.query("DATA_YEAR >= 2015 & DATA_YEAR <= 2018").groupby(['STATE_NAME']).agg('count')
df3 = df3.drop(columns = ['DATA_YEAR'])
df3 = df3.rename(columns = {'BIAS_DESC': 'TOTAL_COUNT_1518'})


df4 = df.query("DATA_YEAR >= 2015 & DATA_YEAR <= 2018 & BIAS_DESC == 'Anti-Asian'").groupby(["STATE_NAME"]).count()
df4 = df4.drop(columns = ['DATA_YEAR'])
df4 = df4.rename(columns = {'BIAS_DESC': 'TOTAL_ASIAN_COUNT_1518'})
df5 = pd.merge(df3,df4,on='STATE_NAME', how='inner')
df5['ASIAN_RATE_1518'] = df5['TOTAL_ASIAN_COUNT_1518']/df5['TOTAL_COUNT_1518']
df5.reset_index(inplace=True)
df5 = df5.rename(columns = {'STATE_NAME': 'State'})
df_twt = pd.read_csv("https://raw.githubusercontent.com/visualization-project-group/surprise-map-assignment/master/tweeter_data.csv")

df_comb = pd.merge(df5,df_twt, on = 'State', how='inner')
df_comb

,State,TOTAL_COUNT_1518,TOTAL_ASIAN_COUNT_1518,ASIAN_RATE_1518,Minorities,White,Black,Arab,Hispanic,Asian
0,Alaska,28,1,0.035714,0.384,0.463,0.440,0.529,0.120,0.078
1,Arizona,926,9,0.009719,0.379,0.445,0.426,0.518,0.120,0.076
2,California,3937,112,0.028448,0.362,0.450,0.429,0.463,0.116,0.069
3,Colorado,386,9,0.023316,0.385,0.454,0.429,0.493,0.130,0.067
4,Connecticut,408,19,0.046569,0.429,0.461,0.466,0.508,0.140,0.075
5,Delaware,76,1,0.013158,0.456,0.476,0.488,0.511,0.125,0.089
6,Florida,470,4,0.008511,0.412,0.450,0.454,0.534,0.125,0.077
7,Georgia,153,2,0.013072,0.448,0.456,0.471,0.528,0.117,0.073
8,Hawaii,44,6,0.136364,0.320,0.416,0.424,0.488,0.102,0.074
9,Illinois,394,6,0.015228,0.412,0.450,0.469,0.470,0.112,0.071
10,Indiana,340,5,0.014706,0.425,0.461,0.472,0.525,0.107,0.065
11,Iowa,48,3,0.062500,0.359,0.408,0.421,0.511,0.084,0.058
12,Kansas,266,4,0.015038,0.379,0.437,0.431,0.517,0.103,0.064
13,Kentucky,1018,9,0.008841,0.421,0.441,0.461,0.532,0.108,0.074
14,Louisiana,155,1,0.006452,0.463,0.459,0.479,0.515,0.111,0.069
15,Maine,131,2,0.015267,0.371,0.412,0.366,0.493,0.167,0.079
16,Maryland,233,3,0.012876,0.444,0.461,0.473,0.459,0.139,0.077
17,Massachusetts,1609,46,0.028589,0.381,0.446,0.431,0.464,0.121,0.073
18,Michigan,1605,16,0.009969,0.448,0.463,0.488,0.485,0.116,0.066
19,Minnesota,498,17,0.034137,0.359,0.444,0.376,0.490,0.113,0.067
20,Mississippi,79,1,0.012658,0.466,0.453,0.485,0.547,0.110,0.075
21,Missouri,367,5,0.013624,0.398,0.440,0.439,0.522,0.101,0.071
22,Nebraska,128,2,0.015625,0.368,0.448,0.426,0.507,0.114,0.059
23,Nevada,137,2,0.014599,0.383,0.449,0.437,0.536,0.117,0.076
24,New Hampshire,70,3,0.042857,0.374,0.443,0.385,0.550,0.126,0.078
25,New Jersey,1663,39,0.023452,0.411,0.458,0.457,0.495,0.123,0.076
26,New Mexico,97,2,0.020619,0.351,0.439,0.425,0.512,0.123,0.073
27,New York,2174,43,0.019779,0.364,0.451,0.422,0.463,0.118,0.061
28,North Carolina,616,6,0.009740,0.436,0.461,0.466,0.514,0.125,0.066
29,Ohio,1639,13,0.007932,0.438,0.456,0.474,0.511,0.110,0.063
30,Oklahoma,132,1,0.007576,0.391,0.437,0.434,0.506,0.106,0.068
31,Oregon,482,5,0.010373,0.350,0.456,0.380,0.483,0.121,0.060
32,Pennsylvania,272,5,0.018382,0.426,0.462,0.469,0.502,0.127,0.074
33,Rhode Island,54,3,0.055556,0.401,0.450,0.449,0.486,0.116,0.073
34,South Carolina,238,1,0.004202,0.443,0.459,0.470,0.536,0.117,0.069
35,Tennessee,670,5,0.007463,0.434,0.382,0.472,0.539,0.099,0.069
36,Texas,961,20,0.020812,0.418,0.445,0.455,0.508,0.119,0.072
37,Utah,209,1,0.004785,0.330,0.433,0.379,0.460,0.109,0.069
38,Vermont,108,2,0.018519,0.353,0.433,0.340,0.471,0.182,0.082
39,Virginia,655,10,0.015267,0.415,0.453,0.452,0.465,0.129,0.072
40,Washington,1701,51,0.029982,0.357,0.452,0.407,0.492,0.117,0.068
41,West Virginia,206,2,0.009709,0.395,0.399,0.440,0.531,0.105,0.069
42,Wisconsin,185,1,0.005405,0.409,0.457,0.466,0.508,0.108,0.077

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from mpld3 import plugins
import mpld3

fig, ax = plt.subplots()

labels = []
sizes = []
colors = np.random.random(43)
for i, row in df_comb.iterrows():
    label = [row['State']]
    points = ax.scatter(row['ASIAN_RATE_1518'], row['Asian'], s=row['TOTAL_ASIAN_COUNT_1518']*20, alpha=0.5, label = row['State'])
    plugins.connect(fig, plugins.PointLabelTooltip(points, label))


'''def piechart_plot(axis_obj, state, data):
    pi_sizes = [df_twt.loc[df_twt['State'] == state]['Asian'][1]*100,
                           df_twt.loc[df_twt['State'] == state]['White'][1]*100,
                           df_twt.loc[df_twt['State'] == state]['Black'][1]*100,
                           df_twt.loc[df_twt['State'] == state]['Hispanic'][1]*100,
                           df_twt.loc[df_twt['State'] == state]['Arab'][1]*100,
                           df_twt.loc[df_twt['State'] == state]['Minorities'][1]*100]
    pi_labels = ('Asian', 'White', 'Black', 'Hispanic', 'Arab', 'Minorities')
    pi_explode = (0.1, 0, 0, 0, 0, 0) 
    pi_chart = axis_obj.pie(pi_sizes)'''


    

ax.set_xlabel("Asian Hate Crime Rate")
ax.set_ylabel("Asian Hate Rate based on twitter data")
ax.grid(color='lightgray', alpha=0.3)

# tooltip = plugins.PointLabelTooltip(points, labels)

ax.set_title("anti-Asian sentiment tweets w.r.t Asian Hate Crime rate")

mpld3.display(fig)

ModuleNotFoundError: No module named 'mpld3'